version: '3.9'
services:
  web:
    build: .
    command: gunicorn vide.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./vide:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: videgrenier
      POSTGRES_USER: vgkuser
      POSTGRES_PASSWORD: vgkpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
