# Generated by Django 4.2.7 on 2025-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Token de réinitialisation du mot de passe', max_length=128, null=True),
        ),
    ]
