# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_searchalert_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visitor_name',
            field=models.CharField(blank=True, help_text='Nom du visiteur (pour commandes sans compte)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='visitor_email',
            field=models.EmailField(blank=True, help_text='Email du visiteur (pour commandes sans compte)', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='visitor_phone',
            field=models.CharField(blank=True, help_text='Téléphone du visiteur (pour commandes sans compte)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_preferred',
            field=models.BooleanField(default=False, help_text='Le visiteur préfère WhatsApp pour contact'),
        ),
    ] 