# Generated by Django 5.2.4 on 2025-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_add_order_pickup_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='visitor_name',
            field=models.CharField(blank=True, help_text='Nom du visiteur (pour commandes sans compte)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='visitor_email',
            field=models.EmailField(blank=True, help_text='Email du visiteur (pour commandes sans compte)', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='visitor_phone',
            field=models.CharField(blank=True, help_text='Téléphone du visiteur (pour commandes sans compte)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_preferred',
            field=models.BooleanField(default=False, help_text='Le visiteur préfère WhatsApp pour contact'),
        ),
    ]
