# Generated by Django 5.2.4 on 2025-07-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_enhance_newsletter_system'),
    ]

    operations = [
    ]
